baseurl: "https://thirsty-mirzakhani-15dc39.netlify.app"
languageCode: "en-us"
title: "OCHS Manuscript Database Project"
theme: "lyngs-xmin"
googleAnalytics: "UA-84972342-1"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
    post: "/post/:year/:month/:day/:slug/"
    note: "/note/:year/:month/:day/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Śākta"
      url: "/sakta/"
      weight: 2
    - name: "Bengali"
      url: "/bengali/"
      weight: 3
    - name: "About / FAQ"
      url: "/about/"
      weight: 4

params:
    description: "OCHS Database Concept proof."
    footer: |
        &copy; Ulrik Lyngs 2020. 
        Powered by [Hugo](https://gohugo.io) and [blogdown](https://bookdown.org/yihui/blogdown/).
