---
title: Śākta
menu: main
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(DT)
# library(googlesheets4)
# gs4_deauth()
 
### publications #####
# manuscript_meta <- read_sheet("https://docs.google.com/spreadsheets/d/10pwVATuDKQDj7_X67Bc_EDO5Wm6wgVvCG8N7fIiC2Y4/edit?usp=sharing",
#            sheet = "texts",
#            col_types = "c")
# manuscript_meta %>% write_csv(here("static", "manuscripts", "manuscript_meta.csv"))

manuscript_meta <- read_csv(here("static", "manuscripts", "manuscript_meta.csv"))
```


<div class="row manuscript-list-page-header">
<div class="col-sm-12">
# Śākta manuscripts
</div>
</div>

<div class="row">
```{block type="col-lg-9 col-md-9 col-sm-6", echo=TRUE}
- This will be the front page to the section of the site where Hindu and Buddhist manuscripts associated with the Śākta Traditions research programme can be browsed

```

```{block type="col-lg-3 col-md-3 col-sm-6", echo=TRUE}
<div class='embed-responsive embed-responsive-16by9'>
<iframe class='embed-responsive-item featured-work-graphic' src='https://player.vimeo.com/video/376577532' allow="fullscreen" allowfullscreen></iframe>
</div>

```

</div>

<div class="row">
<div class="col-sm-12">
<br>

# Select a text

```{r}
manuscript_meta %>% 
  select(-googlesheet_with_text, 
         -googlesheet_id, 
         -Notes,
         -id) %>% 
  #filter(!(Catalogue_id %in% c("test_text_1", "test_text_2"))) %>% 
  arrange(desc(has_content), desc(Date_added)) %>% 
  mutate(Date_added = as.character(Date_added)) %>% 
  mutate(across(-has_content, ~ifelse(has_content == "yes", 
                                                   str_c("<a href='/manuscripts/", Catalogue_id, "/'>", ., "</a>"),
                                                   .))) %>% 
  select(-has_content, -Date_added, -Catalogue_id) %>% 
  datatable(rownames = FALSE,
            escape = FALSE,
            class = 'row-border',
            extensions = 'FixedColumns', 
            options = list(pageLength = 20, scrollX = TRUE, scrollCollapse = TRUE)) 
```
<br>

</div>
</div>