---
exclude_jquery: true
title: "Haṭha[yoga]pradīpikā (HP, HYP)"
sanskritTitle: "हथप्रदिपिक"
transliteratedTitle: "Haṭhapradīpikā"
englishTitle: "Light of Haṭhayoga"
approximateDating: "1450 CE"
manuscriptLanguage: "Sanskrit"
script: "Devanāgarī"
material: "Printed edition"
condition: "Good"
folios: ""
subject: "Tantric Yoga, Haṭhayoga, Kuṇḍalinīyoga, Layayoga, Nādanusandhāna"
physicalLocation: "Private collection (BWO)"
originPlace: "India"
author: "Svātmārāma"
provenance: ""
bibliographyNote: "Svāmī Digambarjī and Pītāmbara Jhā’s edition of Svātmārāma’s Haṭhapradīpikā (Lonāvlā: Kaivalyadhāma Śrīmanmādhava Yogamandira Samiti, 1980)"
codices: ""
transliterators: "Bjarne Wernicke-Olesen, Silje Lyngar Einarsen"
translationEnglish: "https://www.wisdomlib.org/hinduism/book/hatha-yoga-pradipika-english"
translationDanish: "Dorte Effersøe, Elizabeth Rosendahl, Erik Grammagnat, Gitte Poulsen, Jesper Moeslund, Lena Molin, Lisa Bukhave, Lisette Hededal, Sander Rosenkilde, Tanja Louise Jakobsen, Therese Udklit"
googlesheet: "https://docs.google.com/spreadsheets/d/1v-M28WjSn4mt3B6jaOq6qMA6oDqT-j3P62blUOtIzgQ/edit?usp=sharing"
categories:
  - sanskrit
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(DT)
library(here)
source(here("_scripts", "manuscript_layout_text_only.R"))

data_text <- read_csv(here("static", "manuscripts", "hathayogapradipika.csv"))

# count columns to include
count_cols <- data_text %>% 
  slice(1)

cols_include <- count_cols %>% 
  select(chapter, transliteration, starts_with("translation_")) %>% 
  length()

cols_total <- length(count_cols)

cols_hide_nums <- c(1, seq(cols_include + 1, cols_total - 1))

# ensure the DT libraries are included - they are not automatically when looping through datatables
datatable(data_text, extensions = c("Buttons", "ColReorder"), options = list(
    dom = "Bfrtip",
    buttons = I("colvis"),
    colReorder = TRUE))

```

```{r add-text, results="asis"}
create_content(cols_hide = cols_hide_nums)
cat("\n")
```
