---
exclude_jquery: true
catalogueId: mss0001_durgasaptasati
title: "MSS0001 Durgāsaptaśatī"
sanskritTitle: "दुर्गासप्तशती"
transliteratedTitle: "Durgāsaptaśatī (Caṇḍīpāṭha, Devīmāhātmya))"
englishTitle: "700 Stanzas of Durgā"
approximateDating: "19th-20th cent."
manuscriptLanguage: "Sanskrit"
script: "Devanāgarī"
material: ""
condition: ""
folios: ""
subject: ""
physicalLocation: ""
originPlace: ""
author: ""
provenance: ""
bibliographyNote: ""
codices: ""
transliterators: ""
translationEnglish: ""
translationDanish: ""
googlesheet: ""
hasPhotos: yes
hasText: no
categories:
  - sanskrit
---

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(DT)
library(here)
library(glue)
source(here("_scripts", "manuscript_layout_photos_only.R"))
source(here("_scripts/", "manuscript_joint_functions.R"))

photos_folder <- "https://shakta-manuscripts.s3.eu-west-2.amazonaws.com/"

folder_name <- "mss0001_durgasaptasati/medium_resolution/"

photos_medium_resolution <- read_csv(here::here("data", "aws_content.csv")) %>% 
  filter(manuscript == "mss0001_durgasaptasati", high_resolution == FALSE, filepath != "mss0001_durgasaptasati") %>% 
  pull(filename)

photo_info <- tibble(
   photoid = photos_medium_resolution,
   photo_path = str_c(photos_folder, folder_name, photos_medium_resolution)) %>%
   mutate(zoomid = str_c("zoomable", row_number()))

data_text <- NA

```


```{r add-text, results="asis"}
insert_dictionary_iframes()
create_overlay_divs(photo_info)
pwalk(photo_info, create_content)
cat("\n")
initiate_zoom_effect(photo_info)
create_overlay_functions(photo_info)
initialise_lazy_load()
```
