---
exclude_jquery: true
catalogueId: mss0003_svasthani
title: "MSS0003 Svasthānī"
sanskritTitle: "स्वस्थानि"
transliteratedTitle: "Svasthānī"
englishTitle: ""
approximateDating: "19th-20th cent."
manuscriptLanguage: "Sanskrit"
script: "Devanāgarī"
material: ""
condition: ""
folios: ""
subject: ""
physicalLocation: ""
originPlace: ""
author: ""
provenance: ""
bibliographyNote: ""
codices: ""
transliterators: ""
translationEnglish: ""
translationDanish: ""
googlesheet: ""
hasPhotos: yes
hasText: no
categories:
  - sanskrit
---

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(DT)
library(here)
library(glue)
source(here("_scripts", "manuscript_layout_photos_only.R"))

photos_folder <- here("static", "manuscripts", "images", "mss0003_svasthani", "for_manuscript_page")

folder_name <- "mss0003_svasthani/for_manuscript_page/"

photo_info <- tibble(
   photoid = list.files(photos_folder),
   photo_path = str_c("/manuscripts/images/", folder_name, list.files(photos_folder))) %>% 
   mutate(zoomid = str_c("zoomable", row_number()))

data_text <- NA

```

<div id="sanskrit-dictionary">
<a href="javascript:void(0)" class="closebtn-dictionary" onclick="toggleDictionary()">&times;</a>
<iframe src="https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc2/index.php"></iframe>
<p>Via the <a href="https://www.sanskrit-lexicon.uni-koeln.de" target="_blank">Cologne Digital Sanskrit Dictionaries</a></p>
</div>
<div id="sanskrit-dictionary2">
<a href="javascript:void(0)" class="closebtn-dictionary" onclick="toggleDictionary2()">&times;</a>
<iframe src="https://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2020/web/webtc2/index.php"></iframe>
<p>Via the <a href="https://www.sanskrit-lexicon.uni-koeln.de" target="_blank">Cologne Digital Sanskrit Dictionaries</a></p>
</div>
<div id="sanskrit-dictionary-url">
<a href="javascript:void(0)" class="closebtn-dictionary" onclick="toggleDictionaryURL()">&times;</a>
<iframe src="" id="frame-dictionary-url"></iframe>
</div>

```{r add-text, results="asis"}
create_overlay_divs(photo_info)
pwalk(photo_info, create_content)
cat("\n")
initiate_zoom_effect(photo_info)
create_overlay_functions(photo_info)
```
